name: Version Check
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out base branch repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          sparse-checkout: |
            build_settings.json

      - name: Check old build_settings.json version
        run: |
          cd ${{ github.workspace }}
          old_version=( $(jq '.version' build_settings.json))
          echo "Old version is ${old_version:1:${#old_version}-2}"

      - name: Check out current commit repository code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            build_settings.json

      - name: Check current build_settings.json version
        run: |
          cd ${{ github.workspace }}
          version=( $(jq '.version' build_settings.json))
          echo "Current version is ${version:1:${#version}-2}"
