name: Version Check
run-name: Version Check for "${{ github.event.pull_request.title }}"
on: [pull_request_target]

jobs:
  version-fetch:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out base branch repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: old
          sparse-checkout: |
            build_settings.json

      - name: Check out current commit repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: current
          sparse-checkout: |
            build_settings.json

      - name: Check build_settings.json version
        id: version_check
        run: |
          cd ${{ github.workspace }}
          old_version=( $(jq '.version' ./old/build_settings.json))
          current_version=( $(jq '.version' ./current/build_settings.json))
          echo "OLD_VERSION=old_version" >> "$GITHUB_OUTPUT"
          echo "CURRENT_VERSION=current_version" >> "$GITHUB_OUTPUT"
          echo "Old version is ${old_version:1:${#old_version}-2}"
          echo "Current version is ${current_version:1:${#current_version}-2}"
          if [ "${old_version}" != "${current_version}" ]; then
            echo "Version incremented"
          else
            echo "::warning file=build_settings.json,title=Version not incremented::Version not incremented"
          fi

      - name: Comment if version not incremented
        if: steps.setter.outputs.OLD_VERSION == steps.setter.outputs.CURRENT_VERSION
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: version-not-incremented-message
          message: "Version was not incremented. Did you mean to do that?"
          recreate: true

      - name: Delete comment if version was incremented
        if: steps.setter.outputs.OLD_VERSION != steps.setter.outputs.CURRENT_VERSION
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: version-not-incremented-message
          delete: true