name: Version Check
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          sparse-checkout: |
            build_settings.json
      - name: Check current version
        run: |
          cd ${{ github.workspace }}
          version=( $(jq '.version' build_settings.json))
          echo "${version:1:${#version}-2}"
