name: Version Update
run-name: Version Update for "${{ github.event.issue.title }}"
on: 
  issue_comment:
    types: [edited]

jobs:
  call-reusable-workflow:
    uses: makotocchi/github-actions-test/workflows/version_update.yml@main
