name: Version Check
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
